cargo-features = ["edition2024"]

[package]
name = "solana-escrow"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "1.5.7"
solana-program = "1.16.0"
spl-token = { version = "4.0.0", features = ["no-entrypoint"] }
